name: WebdriverIO Tests


on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      testType:
        description: 'Type of test to run (web, api, or both)'
        required: true
        type: choice
        default: both
        options:
          - web
          - api
          - both
      browser:
        description: 'Browser to run tests on (chrome or firefox)'
        required: false
        type: choice
        default: chrome
        options:
          - chrome
          - firefox
          - both

jobs:
  wdio-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        browser: ${{ 
          github.event.inputs.browser == 'both' && fromJSON('["chrome", "firefox"]') ||
          github.event.inputs.browser && fromJSON(format('["{0}"]', github.event.inputs.browser)) ||
          fromJSON('["chrome"]')}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            npm run api:test
            if [ "${{ matrix.browser }}" = "chrome" ]; then
              npm run wdio:chrome
            else
              npm run wdio:firefox
            fi
          else
            if [ "${{ github.event.inputs.testType }}" = "api" ]; then
              npm run api:test
            elif [ "${{ github.event.inputs.testType }}" = "web" ]; then
              if [ "${{ matrix.browser }}" = "chrome" ]; then
                npm run wdio:chrome
              else
                npm run wdio:firefox
              fi
            elif [ "${{ github.event.inputs.testType }}" = "both" ]; then
              npm run api:test
              if [ "${{ matrix.browser }}" = "chrome" ]; then
                npm run wdio:chrome
              else
                npm run wdio:firefox
              fi
            fi
          fi
      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        with:
          name: Tests Results                  # Name of the check run which will be created
          path: './reports/junit-results/*.xml'     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure_results_${{ matrix.browser }}
          path: ./reports/allure-results/
